#!/bin/sh
bits_to_dfs.py $1 /tmp/voice.dfs
#ambe -w /tmp/voice.dfs
ir77_ambe_decode /tmp/voice.dfs /tmp/voice.wav

if hash mplayer 2>/dev/null; then
  mplayer /tmp/voice.wav
else
  aplay /tmp/voice.wav
fi
