#!/bin/sh

pdir=`pwd`
file=$1

dir=`basename ${file%.raw}`

if [ ! -d $dir ] ; then
	mkdir $dir
	cd $dir

	$pdir/detector-fft.py ../$file

	rm *-f*.raw
	for a in *.raw ; do
	$pdir/cut-and-downmix-2.py $a
	done |tee cut-output|grep "File:"

#	exit
else
	cd $dir
fi

for a in *-f*.raw ; do 
$pdir/demod.py $a
done |tee demod-output |grep access
