#!/bin/sh


case "$1" in 
 -*1*) one=1;;
esac
case "$1" in 
 -*2*) two=1;;
esac
case "$1" in 
 -*3*) three=1;;
esac

case "$1" in 
 -*) noauto=1 ; shift;;
esac

pdir=../../iridium/
file=$1
dir=`basename ${file%.raw}`

if [ -z "$noauto" ] ; then
	if [ ! -d $dir ] ; then
		mkdir $dir
		one=1
	fi
	if [ ! -f $dir/cut-output ] ; then
		two=1
	fi
	if [ ! -f $dir/demod-output ] ; then
		three=1
	fi
fi

cd $dir || { echo "Could not cd $dir" >&2 ; exit ; }

if [ ! -z "$one" ] ; then

	$pdir/detector-fft.py ../$file
fi

if [ ! -z "$two" ] ; then
	rm *-f*.raw
	for a in *.raw ; do
	$pdir/cut-and-downmix-2.py $a
	done |tee cut-output|grep "File:"
fi

if [ ! -z "$three" ] ; then
	for a in *-f*.raw ; do 
	$pdir/demod.py $a
	done |tee demod-output |grep access
fi
