#!/bin/sh

store=data
shutdown=SHUTDOWN
pdir=$(cd $(dirname $0);pwd)

# use epochseconds if possible
scommand=$pdir/epochseconds
if [ ! -x $pdir/epochseconds ] ; then
	(cd $pdir;gcc -O -o epochseconds tools/epochseconds.c)
fi
if [ ! -x $pdir/epochseconds ] ; then
	scommand="date +%s"
fi

# -b (Both)
center=1626354000
rate=500000
char=b
# -s (Pager)
center=1626440000
rate=250000
char=s

len=600
splits=216
ssize=8

samples=$(echo "$rate * $len * $splits"|bc)
splits=$(echo "$ssize * $rate * $len" |bc)



[ ! -d $store ] && mkdir $store

if [ -z "$1" ]  ; then
    echo "Call me with \"record\" or \"process\" as argument"
    exit 1
fi


processrecording(){
        curname=$1
        echo "Processing $curname"
        ts=`date +%s`
        $pdir/doit.pl $curname > ${curname%.*}.out
        cat ${curname%.*}.bits >> all.bits
        if [ -s ${curname%.*}.bits ] ; then
            rm $curname
            rm -rf ${curname%.*}
        else
            echo "produced no bits. Keeping working directory"
            rm $curname
        fi
        mv ${curname%.*}* $store/

        echo "Done with $curname in $(echo "scale=1;($(date +%s) - $ts)/60"|bc) min"
}

if [ "$1" = "process" ] ; then
	while true ; do
		for file in i-*-${char}1.?? ; do
            if [ -f $shutdown ] ; then
                echo "Processor shut down"
                exit 0
            fi
			if [ "$file" = "i-*-${char}1.??" ] ; then
				continue
			fi
			if [ `stat -c %s $file` = $splits ] ; then
				mv $file $file.raw
				processrecording $file.raw
			fi
		done
		sleep 10
	done
	echo "Processor shut down"
    exit 0
fi

if [ "$1" = "processrecording" ] ; then
    file=$2
    case $2 in 
    *.raw) ;;
    *) mv $file $file.raw
        file=$file.raw ;;
    esac
    processrecording $file
fi

if [ "$1" = "record" ] ; then
    while [ ! -f $shutdown ] ; do 
        newname=i-$($scommand)-${char}1.
        uhd_rx_cfile --freq=$center --samp-rate=$rate -A RX2 --gain=50 -N $samples /dev/fd/3 3>&1 1>&2 | split --verbose -b $splits - $newname
        echo "Ended one recording"
    done
    echo "Recorder shut down"
    exit 0
fi
