#!/bin/sh

store=data
shutdown=SHUTDOWN

rate=500000
len=600
splits=216
ssize=8

samples=$(echo "$rate * $len * $splits"|bc)
splits=$(echo "$ssize * $rate * $len" |bc)
center=1626354000

[ ! -d $store ] && mkdir $store

processrecording(){
        curname=$1
        ../iridium/doit.pl $curname
        cat ${curname%.*}.bits >> all.bits
        rm $curname
		rm -rf ${curname%.*}
        mv ${curname%.*}* $store/
        echo "Done with $curname"
}

processer(){
	while [ ! -f $shutdown ] ; do 
		sleep 10
		for file in i-*-b1.* ; do
			if [ "$file" = "i-*-b1.*" ] ; then
				continue
			fi
			if [ `stat -c %s $file` = $splits ] ; then
				mv $file $file.raw
				processrecording $file.raw
			fi
		done
	done
	echo "Processor shut down"
}


processer &
ppid=$!

trap "touch SHUTDOWN;kill $ppid" 3

# recorder
while [ ! -f $shutdown ] ; do 
    newname=i-$(date +%s)-b1.
    newname=i-$(../iridium/epochseconds)-b1.
    uhd_rx_cfile --freq=$center --samp-rate=$rate -A RX2 --gain=50 -N $samples /dev/fd/3 3>&1 1>&2 | split -b $splits - $newname
done

echo "Waiting for Processor"
wait $ppid
