#!/bin/sh

base=""

while true
do
  case $1 in
    -r)  # set sample rate
        r=$2
        shift; shift
        ;;
    -b) # set base freq
        f=$2
		base=yes
        shift; shift
        ;;
    -1) # Stage 1 file (detector output)
		file="*/*-$2.det"
		base=yes
        shift; shift
        ;;
    -2) # Stage 2 file (downmix output)
		file="*/*-$2-*.cut"
        shift; shift
        ;;
    *)
        break
        ;;
  esac
done

if [ -z "$file" ] ; then
	# Heuristic
	if [ ! -f "$1" ] ; then 
		file="*/*-$1.det"
		base=yes
	else
		file="$1"
	fi
fi

file=$(echo $file)

# Try to guess rate/freq
if [ -z "$r" ] ; then
	case $file in 
	*-v*)
		f=1626270833
		r=2000000
		;;
	*-s*)
		f=1626440000
		r=250000
		;;
	*-r*)
		f=1626270000
		r=250000
		;;
	*-b*)
		f=1626354000
		r=500000
		;;
	*-t*)
		f=1626000000
		r=1000000
		;;
	*)
		echo "No idea... " >&2
		f=0
		r=1000000
		;;
	esac
fi

if [ "$base" = "yes" ] ; then
	base="-basefrequency $f"
fi

if [ ! -f "$file" ] ; then 
	echo "Can't find $file" >&2
	exit 1
fi

case $file in
	*.rtl) fmt="-e unsigned-integer -b 8";;
	*) fmt="-e floating-point -b 32";;
esac

tmp=/tmp/$(echo $(basename $file)|sed 's!/!_!g').wav

sox -r $r $fmt -c 2 -t raw $file $tmp
baudline -quadrature -samplerate $r $base -fftsize 1024 -channels 2 -flipcomplex $tmp
rm $tmp
