#!/bin/sh

DATE=`date -Iseconds`
files="iridium-NEXT"
[ ! -z "$1" ] && files="$file iridium"

[ ! -z $(dirname $0) ] && cd $(dirname $0)

for f in $files ; do
	if [ -f $f.txt ] ; then
		mv $f.txt $f.old
	else
		touch $f.old
	fi
	curl -sL -o ${f}.txt "http://celestrak.org/NORAD/elements/gp.php?GROUP=${f}&FORMAT=tle"
	if cmp -s $f.old $f.txt ; then
		echo "$f is unchanged"
		rm $f.old
	else
		echo "Saving new version of $f"
		cp $f.txt tle/${f}-$DATE.txt
	fi
done
